#Archivo de configuración actualizado
#Tue Apr 08 00:41:00 GMT-05:00 2025
aplicar-guia-etica-estricta=true
duracion-maxima-consulta=60
duracion-minima-consulta=15
edad-maxima-paciente=120
edad-minima-paciente=2
formato-fecha=dd/MM/yyyy
formato-hora=HH\:mm
idioma-predeterminado=es
idiomas-soportados=es-en-fr
lenguaje-explicito=false
periodo-retencion-datos=365
